%YAML 1.3
---
- Feature: GESTURE 2
- TestBytes: [3, 4, -128, 127]
- Rule:
  - TestBytes: [3, 4, 1, 127]
  - KeyPress:
    - XF86_AudioRaiseVolume
    - click
- Rule:
  - TestBytes: [3, 4, -128, -1]
  - KeyPress:
    - XF86_AudioLowerVolume
    - click
...
---
- Test: [thumb_wheel_up, 5]
- KeyPress:
  - XF86_AudioRaiseVolume
  - click
...
---
- Test: [thumb_wheel_down, 5]
- KeyPress:
  - XF86_AudioLowerVolume
  - click
...
